
services:

  app:
    container_name: opready
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      # CHANGED: Allow overriding resources via .env, default to standard folder
      - ${UI_RESOURCES_PATH:-./public/resources}:/app/public/resources
    env_file:         
      - .env  
    networks:
      - opready 
    command: node server.js
    restart: unless-stopped
networks:
  opready:
